-- MySQL Script generated by MySQL Workbench
-- Sun Apr 23 13:08:20 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kfarmer_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kfarmer_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kfarmer_db` DEFAULT CHARACTER SET utf8 ;
USE `kfarmer_db` ;

-- -----------------------------------------------------
-- Table `kfarmer_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kfarmer_db`.`user` ;

CREATE TABLE IF NOT EXISTS `kfarmer_db`.`user` (
  `id` INT NOT NULL,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kfarmer_db`.`affiliation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kfarmer_db`.`affiliation` ;

CREATE TABLE IF NOT EXISTS `kfarmer_db`.`affiliation` (
  `id` INT NOT NULL,
  `institution` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kfarmer_db`.`author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kfarmer_db`.`author` ;

CREATE TABLE IF NOT EXISTS `kfarmer_db`.`author` (
  `user_id` INT NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `affiliation` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `affiliated_idx` (`affiliation` ASC),
  CONSTRAINT `id`
    FOREIGN KEY (`user_id`)
    REFERENCES `kfarmer_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `affiliated`
    FOREIGN KEY (`affiliation`)
    REFERENCES `kfarmer_db`.`affiliation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kfarmer_db`.`RICodes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kfarmer_db`.`RICodes` ;

CREATE TABLE IF NOT EXISTS `kfarmer_db`.`RICodes` (
  `code` INT NOT NULL,
  `interest` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kfarmer_db`.`editor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kfarmer_db`.`editor` ;

CREATE TABLE IF NOT EXISTS `kfarmer_db`.`editor` (
  `user_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_editor_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_editor_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `kfarmer_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kfarmer_db`.`manuscript`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kfarmer_db`.`manuscript` ;

CREATE TABLE IF NOT EXISTS `kfarmer_db`.`manuscript` (
  `id` INT NOT NULL,
  `author_id` INT NOT NULL,
  `editor_id` INT NOT NULL,
  `RICodes_code` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `status` INT NOT NULL,
  `timestamp` DATETIME NOT NULL,
  `pageCount` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `owner_idx` (`author_id` ASC),
  INDEX `fk_manuscript_RICodes1_idx` (`RICodes_code` ASC),
  INDEX `fk_manuscript_editor1_idx` (`editor_id` ASC),
  CONSTRAINT `owner`
    FOREIGN KEY (`author_id`)
    REFERENCES `kfarmer_db`.`author` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_manuscript_RICodes1`
    FOREIGN KEY (`RICodes_code`)
    REFERENCES `kfarmer_db`.`RICodes` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_manuscript_editor1`
    FOREIGN KEY (`editor_id`)
    REFERENCES `kfarmer_db`.`editor` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kfarmer_db`.`reviewer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kfarmer_db`.`reviewer` ;

CREATE TABLE IF NOT EXISTS `kfarmer_db`.`reviewer` (
  `user_id` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `affiliation` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `affiliation_idx` (`affiliation` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `kfarmer_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `affiliation`
    FOREIGN KEY (`affiliation`)
    REFERENCES `kfarmer_db`.`affiliation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kfarmer_db`.`interests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kfarmer_db`.`interests` ;

CREATE TABLE IF NOT EXISTS `kfarmer_db`.`interests` (
  `reviewer_id` INT NOT NULL,
  `RICodes_code` INT NOT NULL,
  PRIMARY KEY (`reviewer_id`, `RICodes_code`),
  INDEX `fk_interests_RICodes1_idx` (`RICodes_code` ASC),
  INDEX `fk_interests_reviewer1_idx` (`reviewer_id` ASC),
  CONSTRAINT `fk_interests_RICodes1`
    FOREIGN KEY (`RICodes_code`)
    REFERENCES `kfarmer_db`.`RICodes` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_interests_reviewer1`
    FOREIGN KEY (`reviewer_id`)
    REFERENCES `kfarmer_db`.`reviewer` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kfarmer_db`.`review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kfarmer_db`.`review` ;

CREATE TABLE IF NOT EXISTS `kfarmer_db`.`review` (
  `manuscript_id` INT NOT NULL,
  `reviewer_id` INT NOT NULL,
  `dateSent` DATETIME NOT NULL,
  PRIMARY KEY (`manuscript_id`, `reviewer_id`),
  INDEX `manuscript_idx` (`manuscript_id` ASC),
  INDEX `reviewer_idx` (`reviewer_id` ASC),
  CONSTRAINT `manuscript`
    FOREIGN KEY (`manuscript_id`)
    REFERENCES `kfarmer_db`.`manuscript` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `reviewer`
    FOREIGN KEY (`reviewer_id`)
    REFERENCES `kfarmer_db`.`reviewer` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kfarmer_db`.`feedback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kfarmer_db`.`feedback` ;

CREATE TABLE IF NOT EXISTS `kfarmer_db`.`feedback` (
  `manuscript_id` INT NOT NULL,
  `reviewer_id` INT NOT NULL,
  `appropriateness` INT NOT NULL,
  `clarity` INT NOT NULL,
  `methodology` INT NOT NULL,
  `contribution` INT NOT NULL,
  `recommendation` TINYINT NOT NULL,
  `dateReceived` DATETIME NOT NULL,
  PRIMARY KEY (`manuscript_id`, `reviewer_id`),
  INDEX `fk_feedback_review1_idx` (`manuscript_id` ASC, `reviewer_id` ASC),
  CONSTRAINT `fk_feedback_review1`
    FOREIGN KEY (`manuscript_id` , `reviewer_id`)
    REFERENCES `kfarmer_db`.`review` (`manuscript_id` , `reviewer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kfarmer_db`.`issue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kfarmer_db`.`issue` ;

CREATE TABLE IF NOT EXISTS `kfarmer_db`.`issue` (
  `id` INT NOT NULL COMMENT 'Volume might be monotonically increasing, in which case, it should be the PK of this table.',
  `year` INT NOT NULL,
  `period` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kfarmer_db`.`acceptance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kfarmer_db`.`acceptance` ;

CREATE TABLE IF NOT EXISTS `kfarmer_db`.`acceptance` (
  `manuscript_id` INT NOT NULL,
  `issue_id` INT NOT NULL,
  `position` INT NOT NULL,
  `pageNum` INT NOT NULL,
  PRIMARY KEY (`manuscript_id`),
  INDEX `for_idx` (`manuscript_id` ASC),
  INDEX `published in_idx` (`issue_id` ASC),
  CONSTRAINT `for`
    FOREIGN KEY (`manuscript_id`)
    REFERENCES `kfarmer_db`.`manuscript` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `published in`
    FOREIGN KEY (`issue_id`)
    REFERENCES `kfarmer_db`.`issue` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kfarmer_db`.`contributors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kfarmer_db`.`contributors` ;

CREATE TABLE IF NOT EXISTS `kfarmer_db`.`contributors` (
  `manuscript_id` INT NOT NULL,
  `order` INT NOT NULL,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  INDEX `fk_manuscript_has_author_manuscript1_idx` (`manuscript_id` ASC),
  PRIMARY KEY (`manuscript_id`, `order`),
  CONSTRAINT `fk_manuscript_has_author_manuscript1`
    FOREIGN KEY (`manuscript_id`)
    REFERENCES `kfarmer_db`.`manuscript` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kfarmer_db`.`publish`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kfarmer_db`.`publish` ;

CREATE TABLE IF NOT EXISTS `kfarmer_db`.`publish` (
  `issue_id` INT NOT NULL,
  `publishDate` DATETIME NOT NULL,
  INDEX `fk_publish_issue1_idx` (`issue_id` ASC),
  PRIMARY KEY (`issue_id`),
  CONSTRAINT `fk_publish_issue1`
    FOREIGN KEY (`issue_id`)
    REFERENCES `kfarmer_db`.`issue` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
